name: Deploy with Telegram Secrets
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create config file
        run: |
          mkdir -p js
          echo "export const TELEGRAM = {
            BOT_TOKEN: '${{ secrets.TELEGRAM_BOT_TOKEN }}',
            CHAT_ID: '${{ secrets.TELEGRAM_CHAT_ID }}'
          };" > .RERRL/script/config.js
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./